services:
  - type: python
    name: my-python-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt  # Aquí aseguras que pip use el archivo requirements.txt
    startCommand: gunicorn app:app  # Este es el comando para iniciar tu aplicación
